tap "koekeishiya/formulae/"

cask "obsidian"
cask "rectangle-pro"
cask "mission-control-plus"
cask "topnotch"
cask "dozer"
cask "alt-tab"
cask "monitorcontrol"
cask "middle"
cask "discretescroll"
cask "spotify"
cask "whatsapp"
cask "1password"
cask "spaceid"
cask "karabiner-elements"
cask "iterm2"

brew "tmux"
brew "neovim", args: ['HEAD']
brew "jq"
brew "lazygit"
brew "lazydocker"
brew "fzf"
brew "z"
brew "n"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "yabai"
brew "skhd"
brew "starship"
brew "docker"
brew "make"
brew "rust"
