#!/bin/zsh

# Java
#export 
JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home"
#export PATH="$HOME/.jenv/bin:$PATH"
#eval "$(jenv init -)"

# Android
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools

# IDE settings
alias code="/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code"
export LANG=en_US.UTF-8 # For some reason IntelliJ terminal displays ghost characters without this

# LunarVim
export PATH=$PATH:$HOME/.local/bin

# NVM
# export NVM_DIR="$HOME/.nvm"
#   [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
#   [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

fpath=($fpath "${HOME}/.zfunctions") # No idea what this does
