#!/usr/bin/env sh

# Focus window
cmd - h : yabai -m window --focus west
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east

# Swap window
shift + cmd - h : yabai -m window --swap west
shift + cmd - j : yabai -m window --swap south
shift + cmd - k : yabai -m window --swap north
shift + cmd - l : yabai -m window --swap east

# Move window to space
shift + cmd - 1 : yabai -m window --space 1; yabai -m space --focus 1
shift + cmd - 2 : yabai -m window --space 2; yabai -m space --focus 2
shift + cmd - 3 : yabai -m window --space 3; yabai -m space --focus 3
shift + cmd - 4 : yabai -m window --space 4; yabai -m space --focus 4
shift + cmd - 5 : yabai -m window --space 5; yabai -m space --focus 5
shift + cmd - 6 : yabai -m window --space 6; yabai -m space --focus 6

# Focus space
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6

# Focus recent space
cmd + ctrl - o : yabai -m space --focus recent

# Focus monitor
cmd + ctrl - n  : yabai -m display --focus next

# Send window to monitor and follow focus
cmd + shift - n  : yabai -m window --display next; yabai -m display --focus next

# Full screen
cmd - return : yabai -m window --toggle zoom-fullscreen

# Toggle float
cmd + ctrl - t : yabai -m window --toggle float;\
          yabai -m window --grid 4:4:1:1:2:2

# Balance windows
cmd - b : yabai -m space --balance
