# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json

os:
  editPreset: "nvim"
  openLink: open "$(echo "{{link}}" | sed 's/%2F/\//g')"
gui:
  nerdFontsVersion: "3"
keybinding:
  commits:
    moveDownCommit: "<c-n>"
    moveUpCommit: "<c-p>"
services:
  "gitlab.inverselink.com": "gitlab:gitlab.inverselink.com"
