# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

os:
  editPreset: "nvim-remote"
  openLink: open "$(echo "{{link}}" | sed 's/%2F/\//g')"
gui:
  nerdFontsVersion: "3"
  border: rounded
  theme:
      activeBorderColor:
          - "#5ef1ff"
      inactiveBorderColor:
          - "#7b8496"
      searchingActiveBorderColor:
          - "#ff5ef1"
      optionsTextColor:
          - "#3c4048"
      selectedLineBgColor:
          - "#3c4048"
      cherryPickedCommitBgColor:
          - "#3c4048"
      cherryPickedCommitFgColor:
          - "#ff5ea0"
      unstagedChangesColor:
          - "#ffbd5e"
      defaultFgColor:
          - "#ffffff"
keybinding:
  commits:
    moveDownCommit: "<c-n>"
    moveUpCommit: "<c-p>"
services:
  "gitlab.inverselink.com": "gitlab:gitlab.inverselink.com"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
