[colors.bright]
black = "#1a1a1a"
blue = "#8fc6f4"
cyan = "#4bced8"
green = "#a9d89d"
magenta = "#e089e7"
red = "#f38897"
white = "#c8cdd5"
yellow = "#edd4a6"

[colors.cursor]
cursor = "#d55fde"
text = "CellBackground"

[colors.normal]
black = "#000000"
blue = "#61afef"
cyan = "#2bbac5"
green = "#89ca78"
magenta = "#d55fde"
red = "#ef596f"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.primary]
background = "#000000"
foreground = "#abb2bf"

[colors.selection]
background = "#434852"
text = "CellForeground"

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "transparent"
dynamic_padding = true
option_as_alt = "OnlyLeft"

[window.padding]
x = 16
y = 16
