# [colors.bright]
# black = "#1a1a1a"
# blue = "#8fc6f4"
# cyan = "#4bced8"
# green = "#a9d89d"
# magenta = "#e089e7"
# red = "#f38897"
# white = "#c8cdd5"
# yellow = "#edd4a6"
#
# [colors.cursor]
# cursor = "#d55fde"
# text = "CellBackground"
#
# [colors.normal]
# black = "#000000"
# blue = "#61afef"
# cyan = "#2bbac5"
# green = "#89ca78"
# magenta = "#d55fde"
# red = "#ef596f"
# white = "#abb2bf"
# yellow = "#e5c07b"
#
# [colors.primary]
# background = "#000000"
# foreground = "#abb2bf"
#
# [colors.selection]
# background = "#434852"
# text = "CellForeground"
#
[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "transparent"
dynamic_padding = true
option_as_alt = "OnlyLeft"

[window.padding]
x = 16
y = 16
# cyberdream theme for Alacritty
[[colors.indexed_colors]]
color = "0xffbd5e"
index = 16

[[colors.indexed_colors]]
color = "0xff6e5e"
index = 17

[colors.bright]
black = "0x3c4048"
blue = "0x5ea1ff"
cyan = "0x5ef1ff"
green = "0x5eff6c"
magenta = "0xbd5eff"
red = "0xff6e5e"
white = "0xffffff"
yellow = "0xf1ff5e"

[colors.normal]
black = "0x16181a"
blue = "0x5ea1ff"
cyan = "0x5ef1ff"
green = "0x5eff6c"
magenta = "0xbd5eff"
red = "0xff6e5e"
white = "0xffffff"
yellow = "0xf1ff5e"

[colors.primary]
background = "0x16181a"
foreground = "0xffffff"

[colors.selection]
background = "0x3c4048"
foreground = "0xffffff"
