#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Manage layout by default
yabai -m config layout bsp

# Mouse support
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# Padding
yabai -m config top_padding    16
yabai -m config bottom_padding 16
yabai -m config left_padding   16
yabai -m config right_padding  16
yabai -m config window_gap     8

# Only floating windows have shadows
yabai -m config window_shadow float

# Disable managing
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Karabiner(.*)$" manage=off
yabai -m rule --add app="^iTerm2$" title="^Preferences$" manage=off
yabai -m rule --add app="^Google Chrome$" title="^Activate Security Key(.*)$" manage=off
yabai -m rule --add app="^Arc$" title="^Picture in Picture$" manage=off
yabai -m rule --add app="^Mail$" title!="^Inbox(.*)$" manage=off

